services:
  alfa_bot:
    container_name: alfa_bot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - alfa_network
    volumes:
      - ./uploads:/app/uploads
    

networks:
  alfa_network:
    driver: bridge