services:
  alfa_bot:
    container_name: alfa_bot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres_server
    networks:
      - alfa_network

  postgres_server:
    image: postgres:latest
    container_name: postgres_server
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=alfa_bot
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    networks:
      - alfa_network

volumes:
  postgres_data:

networks:
  alfa_network:
    driver: bridge